<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-25 at 21:18:04.
 */
class AccountDetailsFormTest extends CTestCase {

    /**
     * @var AccountDetailsForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AccountDetailsForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AccountDetailsForm::rules
     * @todo   Implement testRules().
     */
    public function testRules() {
        // Remove the following lines when you implement this test.
        $this->assertInternalType('array', $this->object->rules());
                $this->assertEquals(array(
                array('account', 'required'),
            ), $this->object->rules());
    }

    /**
     * @covers AccountDetailsForm::attributeLabels
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels() {
        // Remove the following lines when you implement this test.
            $this->assertInternalType('array', $this->object->attributeLabels());
            $this->assertEquals(array(
                'account'=>Yii::t('app', 'Cuenta'),
            ), $this->object->attributeLabels());
    }

    /**
     * @covers AccountDetailsForm::formConfig
     * @todo   Implement testFormConfig().
     */
    public function testFormConfig() {
        
        $this->assertEquals(array(
                'showErrorSummary'=>false,
			'elements'=>array(
				'account'=>array(
					'type'=>'dropdownlist',
					'items'=>'A',
					'empty'=>'',
				),
			),
			'buttons'=>array(
				'submit'=>array(
					'id'=>'submit',
					'buttonType'=>'submit',
					'context'=>'primary',
					'label'=>'Ver detalles',
				),
				'cancel'=>array(
					'buttonType'=>'link',
					'context'=>'danger',
					'label'=>'Cancelar',
					'url'=>array('/site/index'),
				),
			),
            ), $this->object->formConfig($accountOptions='A'));
        
    }

}
