<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-22 at 20:50:58.
 */
class AccountBalanceFormTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AccountBalanceForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AccountBalanceForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AccountBalanceForm::rules
     * @todo   Implement testRules().
     */
    public function testRules() {
        // Remove the following lines when you implement this test.
            $this->assertInternalType('array', $this->object->rules());
            $this->assertEquals(array(       
            array('account, days', 'required'),
            array('days', 'numerical', 'integerOnly'=>true, 'min'=>0, 'max'=>180),
            ), $this->object->rules());
    }

    /**
     * @covers AccountBalanceForm::attributeLabels
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels() {
        // Remove the following lines when you implement this test.
        $this->assertInternalType('array', $this->object->attributeLabels());
        $this->assertEquals(array(       
        'account'=>Yii::t('app', 'Cuenta'),
	'days'=>Yii::t('app', 'Días'),
        ), $this->object->attributeLabels());
    }

    /**
     * @covers AccountBalanceForm::formConfig
     * @todo   Implement testFormConfig().
     */
    public function testFormConfig() {
        // Remove the following lines when you implement this test.
        $this->assertInternalType('array', $this->object->formConfig($accounts='1'));
        $this->assertEquals(array(       
        'elements'=>array(
                'account'=>array(
                        'type'=>'dropdownlist',
                        'items'=>'A',
                ),
                'days'=>array(
                        'type'=>'text',
                ),
        ),
        'buttons'=>array(
                'submit'=>array(
                        'id'=>'submit',
                        'buttonType'=>'submit',
                        'context'=>'primary',
                        'label'=>'Consultar Saldos',
                        'url'=>array('checkbooks'),
                ),
                'cancel'=>array(
                        'context'=>'danger',
                        'label'=>'Cancelar',
                        'url'=>array('/site/index'),
                ),
        ),
        ), $this->object->formConfig($accounts='A'));
    }

}
