<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-22 at 17:24:45.
 */
class ChangePasswordFormTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ChangePasswordForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ChangePasswordForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ChangePasswordForm::rules
     * @todo   Implement testRules().
     */
    public function testRules() {
        // Remove the following lines when you implement this test.
        $this->assertInternalType('array', $this->object->rules());
        $this->assertEquals(array(
        array('currentPassword, newPassword, repeatPassword', 'required'),
        array('repeatPassword', 'compare', 'compareAttribute'=>'newPassword'),
        array('newPassword', 'length', 'min'=>4),
        ), $this->object->rules());
    }

    /**
     * @covers ChangePasswordForm::attributeLabels
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels() {
        // Remove the following lines when you implement this test.
        $this->assertInternalType('array', $this->object->attributeLabels());
        $this->assertEquals(array(
        'currentPassword'=>'Clave antigua',
        'newPassword'=>'Nueva clave',
        'repeatPassword'=>'Repetir nueva clave',
        ), $this->object->attributeLabels());
    }

    /**
     * @covers ChangePasswordForm::formConfig
     * @todo   Implement testFormConfig().
     */
    public function testFormConfig() {
        // Remove the following lines when you implement this test.
        $this->assertInternalType('array', $this->object->formConfig());
        $this->assertEquals(array(
        'title'=> 'Seleccione una cuenta',
			'showErrorSummary'=>false,
			'attributes'=>array('id'=>'select-account-form'),
			'elements'=>array(
				'currentPassword'=>array(
					'type'=>'password',
				),
				'newPassword'=>array(
					'type'=>'password',
				),
				'repeatPassword'=>array(
					'type'=>'password',
				),
			),
			'buttons'=>array(
				'submit'=>array(
					'id'=>'submit',
					'buttonType'=>'submit',
					'context'=>'primary',
					'label'=>'Enviar',
					'url'=>array('checkbooks'),
				),
				'cancel'=>array(
					'context'=>'danger',
					'label'=>'Cancelar',
					'url'=>array('/site/index'),
				),
			),
        ), $this->object->formConfig());
    }

}
