<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-26 at 18:05:35.
 */
class CreditCardPaymentFormTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CreditCardPaymentForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CreditCardPaymentForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers CreditCardPaymentForm::rules
     * @todo   Implement testRules().
     */
    public function testRules() {
        $this->assertInternalType('array', $this->object->rules());
                $this->assertEquals(array(
                array('debitAccount, amount', 'required'),
			array('amount', 'numerical', 'integerOnly'=>true),

			array('creditAccount, confirm', 'safe'),
			array('creditAccount, confirm', 'required', 'on'=>'confirm'),
            ), $this->object->rules());
        
    }

    /**
     * @covers CreditCardPaymentForm::attributeLabels
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels() {
        // Remove the following lines when you implement this test.
        $this->assertInternalType('array', $this->object->attributeLabels());
                $this->assertEquals(array(
                'debitAccount'=>Yii::t('app', 'Cuenta débito'),
                'creditAccount'=>Yii::t('app', 'Cuenta crédito'),
                'amount'=>Yii::t('app', 'Monto'),
            ), $this->object->attributeLabels());
    }

    /**
     * @covers CreditCardPaymentForm::formConfig
     * @todo   Implement testFormConfig().
     */
    public function testFormConfig() {
        // Remove the following lines when you implement this test.
        
        $this->assertInternalType('array', $this->object->formConfig($cardDenomination='1', $debitAccountOptions='1'));
                $this->assertEquals(array(
                
                'title'=> 'Pagar Tarjeta "'.'A'.'"',
			'showErrorSummary'=>false,
			'elements'=>array(
				'debitAccount'=>array(
					'type'=>'dropdownlist',
					'items'=>'A',
					'empty'=>'',
				),
				'amount'=>array(
					'type'=>'text',
				),
				
			),
			'buttons'=>array(
				'submit'=>array(
					'buttonType'=>'submit',
					'context'=>'primary',
					'label'=>'Verificar Pago',
				),
				'cancel'=>array(
					'buttonType'=>'link',
					'context'=>'danger',
					'label'=>'Cancelar',
					'url'=>array('/site/index'),
				),
			),
            ), $this->object->formConfig($cardDenomination='A', $debitAccountOptions='A'));
        
    }

    /**
     * @covers CreditCardPaymentForm::hiddenFormConfig
     * @todo   Implement testHiddenFormConfig().
     */
    public function testHiddenFormConfig() {
        // Remove the following lines when you implement this test.
        $this->assertInternalType('array', $this->object->hiddenFormConfig());
                $this->assertEquals(array(
                
                'elements'=>array(
				'debitAccount'=>array(
					'type'=>'hidden',
				),
				'creditAccount'=>array(
					'type'=>'hidden',
				),
				'amount'=>array(
					'type'=>'hidden',
				),
				'confirm'=>array(
					'type'=>'hidden',
				),
				
			),
			'buttons'=>array(
				'submit'=>array(
					'buttonType'=>'submit',
					'context'=>'primary',
					'label'=>'Confirmar Pago',
				),
				'cancel'=>array(
					'buttonType'=>'link',
					'context'=>'danger',
					'label'=>'Cancelar',
					'url'=>array('/site/index'),
				),
			),
            ), $this->object->hiddenFormConfig());
    }

}
